services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Убедитесь что использует правильный файл
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/myapp
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules

  mongo: # ← ЭТОТ СЕРВИС ДОЛЖЕН БЫТЬ ОПРЕДЕЛЕН!
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=myapp

volumes:
  mongo_data:
